name: Bitrix QA

on:
  workflow_dispatch:
    inputs:
      module_id:
        description: "Bitrix module id (vendor.module)"
        required: true
        default: "vendor.module"
      project_root:
        description: "Project root path in repository"
        required: true
        default: "."
      bitrix_root:
        description: "Absolute BITRIX_ROOT for integration suite (optional)"
        required: false
        default: ""
      skip_integration:
        description: "Skip integration suite"
        required: true
        type: boolean
        default: false
  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Install composer dependencies (if present)
        run: |
          set -euo pipefail
          ROOT="${{ github.event.inputs.project_root || '.' }}"
          if [ -f "$ROOT/composer.json" ]; then
            cd "$ROOT"
            composer install --no-interaction --no-progress
          fi

      - name: Run qa_run.py
        id: qa
        run: |
          set -euo pipefail
          ROOT="${{ github.event.inputs.project_root || '.' }}"
          MODULE_ID="${{ github.event.inputs.module_id || 'vendor.module' }}"
          BITRIX_ROOT="${{ github.event.inputs.bitrix_root || '' }}"
          SKIP_INTEGRATION="${{ github.event.inputs.skip_integration || 'false' }}"
          REPORT="$ROOT/tests/qa-run-report-ci.md"

          mkdir -p "$ROOT/tests"

          EXTRA_ARGS=()
          if [ "$SKIP_INTEGRATION" = "true" ]; then
            EXTRA_ARGS+=(--skip-integration)
          fi
          if [ -n "$BITRIX_ROOT" ]; then
            EXTRA_ARGS+=(--bitrix-root "$BITRIX_ROOT")
          fi

          set +e
          python3 skills/bitrix/scripts/qa_run.py \
            --project-root "$ROOT" \
            --module-id "$MODULE_ID" \
            --report "$REPORT" \
            "${EXTRA_ARGS[@]}"
          RC=$?
          set -e

          echo "exit_code=$RC" >> "$GITHUB_OUTPUT"
          echo "report=$REPORT" >> "$GITHUB_OUTPUT"

      - name: Upload QA report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-run-report
          path: ${{ steps.qa.outputs.report }}
          if-no-files-found: warn

      - name: Fail workflow on QA FAIL
        if: steps.qa.outputs.exit_code != '0'
        run: |
          echo "qa_run.py failed: ${{ steps.qa.outputs.exit_code }}"
          exit 1
